# Generated by Django 3.0.8 on 2020-11-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('picture', models.ImageField(blank=True, upload_to='images/')),
                ('residents', models.ManyToManyField(to='accounts.Account')),
            ],
        ),
    ]
