# Generated by Django 3.0.8 on 2020-12-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20201219_1526'),
        ('cities', '0002_city_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='guides',
            field=models.ManyToManyField(related_name='guides', to='accounts.Account'),
        ),
        migrations.AlterField(
            model_name='city',
            name='residents',
            field=models.ManyToManyField(related_name='residents', to='accounts.Account'),
        ),
    ]
