# Generated by Django 3.0.8 on 2020-12-23 11:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20201219_1526'),
        ('cities', '0003_auto_20201223_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Waiting', 'Waiting'), ('In process', 'In process'), ('Finished', 'Finished')], max_length=10)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide', to='accounts.Account')),
                ('requesting_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requesting_user', to='accounts.Account')),
            ],
        ),
    ]
