# Generated by Django 3.0.8 on 2020-12-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0004_guidesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='guide_session',
            field=models.ManyToManyField(blank=True, related_name='guide_session', to='cities.GuideSession'),
        ),
    ]
