# Generated by Django 3.0.8 on 2021-03-10 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0008_auto_20210126_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='guide_session',
        ),
        migrations.DeleteModel(
            name='GuideSession',
        ),
    ]
