# Generated by Django 3.0.8 on 2021-03-10 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_occupation_city'),
        ('cities', '0009_auto_20210310_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestToCreateCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=200, unique=True)),
                ('wiki_link', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('picture', models.CharField(max_length=200)),
                ('requesting_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requesting_user', to='accounts.Account')),
            ],
        ),
    ]
