# Generated by Django 3.1.7 on 2021-03-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20210323_1241'),
        ('cities', '0010_requesttocreatecity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='guides',
            field=models.ManyToManyField(null=True, related_name='guides', to='accounts.Account'),
        ),
    ]
