# Generated by Django 3.1.7 on 2021-03-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0012_auto_20210323_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='latitude',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='city',
            name='longitude',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='requesttocreatecity',
            name='latitude',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='requesttocreatecity',
            name='longitude',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
