# Generated by Django 3.1.7 on 2021-03-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20210324_1037'),
        ('cities', '0013_auto_20210323_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='residents',
            field=models.ManyToManyField(blank=True, related_name='residents', to='accounts.Account'),
        ),
    ]
