# Generated by Django 3.0.8 on 2020-11-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='age',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='account',
            name='cost_preference',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='account',
            name='friends',
            field=models.ManyToManyField(related_name='_account_friends_+', to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='account',
            name='received',
            field=models.ManyToManyField(related_name='_account_received_+', to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='account',
            name='sent',
            field=models.ManyToManyField(related_name='_account_sent_+', to='accounts.Account'),
        ),
    ]
