# Generated by Django 3.0.8 on 2020-11-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201106_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='age',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='account',
            name='cost_preference',
            field=models.CharField(blank=True, default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(blank=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_account_friends_+', to='accounts.Account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_guide',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='account',
            name='received',
            field=models.ManyToManyField(blank=True, related_name='_account_received_+', to='accounts.Account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='sent',
            field=models.ManyToManyField(blank=True, related_name='_account_sent_+', to='accounts.Account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='surname',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
