# Generated by Django 3.0.8 on 2020-11-07 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201106_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='account',
            name='received',
        ),
        migrations.RemoveField(
            model_name='account',
            name='sent',
        ),
        migrations.AddField(
            model_name='account',
            name='friends_list',
            field=models.ManyToManyField(blank=True, related_name='_account_friends_list_+', to='accounts.Account'),
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='accounts.Account')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='accounts.Account')),
            ],
        ),
    ]
