# Generated by Django 3.0.8 on 2020-12-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20201219_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prefereneces',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
