# Generated by Django 3.0.8 on 2021-03-02 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20210215_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128)),
                ('sector', models.CharField(blank=True, choices=[('Highschool', 'Highschool'), ('University', 'University'), ('Working place', 'Working place')], max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='account',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='account',
            name='tiktok_link',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='account',
            name='twitter_link',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='account',
            name='vk_link',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='account',
            name='occupation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occupation', to='accounts.Occupation'),
        ),
    ]
