# Generated by Django 3.0.8 on 2021-03-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20210302_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupation',
            name='amount_of_people',
            field=models.ManyToManyField(blank=True, related_name='amount_of_people', to='accounts.Account'),
        ),
    ]
