# Generated by Django 3.0.8 on 2021-03-06 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_occupation_amount_of_people'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occupation',
            old_name='amount_of_people',
            new_name='related_people',
        ),
    ]
