# Generated by Django 3.0.8 on 2021-03-06 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0008_auto_20210126_1243'),
        ('accounts', '0017_auto_20210306_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupation',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occupation_city', to='cities.City'),
        ),
    ]
