# Generated by Django 3.1.7 on 2021-03-15 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0010_requesttocreatecity'),
        ('accounts', '0019_account_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='living_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city', to='cities.city'),
        ),
        migrations.AlterField(
            model_name='account',
            name='occupation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occupation', to='accounts.occupation'),
        ),
    ]
