# Generated by Django 3.1.7 on 2021-03-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20210315_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, choices=[('City_succes', 'City_succes'), ('City_failure', 'City_failure'), ('Received_friend_request', 'Received_friend_request'), ('Accepted_friend_request', 'Accepted_friend_request'), ('Declined_friend_request', 'Declined_friend_request')], max_length=50)),
                ('message', models.TextField(blank=True)),
            ],
        ),
    ]
