# Generated by Django 3.1.7 on 2021-03-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_notification_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='notifications',
            field=models.ManyToManyField(blank=True, to='accounts.Notification'),
        ),
    ]
