# Generated by Django 3.1.7 on 2021-03-23 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0010_requesttocreatecity'),
        ('accounts', '0023_account_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='living_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city', to='cities.city'),
        ),
        migrations.AlterField(
            model_name='account',
            name='occupation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupation', to='accounts.occupation'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='tag',
            field=models.CharField(blank=True, choices=[('Your city request was accepted', 'Accepted_city_request'), ('Your city request was declined', 'Declined_city_request'), ('Friend request recieved', 'Received_friend_request'), ('Friend request accepted', 'Accepted_friend_request'), ('Friend request declined', 'Declined_friend_request')], max_length=50),
        ),
    ]
