# Generated by Django 3.1.7 on 2021-03-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20210323_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_highschooler',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_student',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_worker',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
