# Generated by Django 3.1.7 on 2021-03-24 10:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20210324_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='interest',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None),
        ),
    ]
