# Generated by Django 3.1.7 on 2021-03-31 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20210327_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='occupation',
        ),
        migrations.AddField(
            model_name='account',
            name='occupations',
            field=models.JSONField(blank=True, default=None),
        ),
    ]
